apiVersion: v1
kind: Service
metadata:
  name: web
  # Add your campusid below
  namespace: campusid-pipeline
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
